steps:
  # Run tests and save to file
  - name: golang:1.23
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
  # [END cloudbuild_go_test_yaml]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/music-plus-click-stream:${SHORT_SHA}','--platform', 'linux/arm64', 'click-stream-processor']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-container-image-web-api'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/music-plus-click-stream:${SHORT_SHA}']