steps:
  - name: 'docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder', '--use' ]
  - name: 'docker'
    args: [ 'buildx', 'build', '--platform', 'linux/arm64', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/music-plus-click-stream:${SHORT_SHA}', '--push', 'click-stream-processor', ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        git clone https://philipgp:${_LIFEKIT_GITHUB_TOKEN_CD_REPO}@github.com/philipgp/LifeKitCD.git -b main
        echo "Updating image tag version ..."
        cd LifeKitCD/music_plus/click_stream_analyzer
        sed -i "s/music-plus-click-stream:[[:alnum:]]*$/music-plus-click-stream:${SHORT_SHA}/g" deployment.yaml
        echo "Pushing changes to k8s manifest repo ..."
        git config --global user.name "Google Cloud Build"
        git config --global user.email "gcb@lifekit.com"
        git add -A
        git commit -m "[Cloud Builder] Updated image tag us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/music-plus-click-stream:$SHORT_SHA from commit ${COMMIT_SHA}"
        git push https://philipgp:${_LIFEKIT_GITHUB_TOKEN_CD_REPO}@github.com/philipgp/LifeKitCD.git main